# Copyright (C) 2015 The Dokdo Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/xolo/era4g/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/xolo/era4g/proprietary/bin/engpc:system/bin/engpc \
    vendor/xolo/era4g/proprietary/bin/ext_data.sh:system/bin/ext_data.sh \
    vendor/xolo/era4g/proprietary/bin/ext_kill.sh:system/bin/ext_kill.sh \
    vendor/xolo/era4g/proprietary/bin/sprd_res_monitor:system/bin/sprd_res_monitor \
    vendor/xolo/era4g/proprietary/bin/slog:system/bin/slog \
    vendor/xolo/era4g/proprietary/bin/slogctl:system/bin/slogctl \
    vendor/xolo/era4g/proprietary/bin/slogmodem:system/bin/slogmodem \
    vendor/xolo/era4g/proprietary/etc/connectivity_calibration.ini:system/etc/connectivity_calibration.ini \
    vendor/xolo/era4g/proprietary/etc/connectivity_configure.ini:system/etc/connectivity_configure.ini \
    vendor/xolo/era4g/proprietary/etc/thermalSensorsConfig.xml:system/etc/thermalSensorsConfig.xml \
    vendor/xolo/era4g/proprietary/bin/inputfreq.sh:system/bin/inputfreq.sh \
    vendor/xolo/era4g/proprietary/bin/recoveryfreq.sh:system/bin/recoveryfreq.sh \
    vendor/xolo/era4g/proprietary/bin/wcnd:system/bin/wcnd \
    vendor/xolo/era4g/proprietary/bin/wcnd_cli:system/bin/wcnd_cli \
    vendor/xolo/era4g/proprietary/bin/download:system/bin/download \
    vendor/xolo/era4g/proprietary/bin/bih_config.sh:system/bin/bih_config.sh \
    vendor/xolo/era4g/proprietary/lib/libsprd_agps_agent.so:system/lib/libsprd_agps_agent.so \
    vendor/xolo/era4g/proprietary/lib/libaudioeffect_jni.so:system/lib/libaudioeffect_jni.so \
    vendor/xolo/era4g/proprietary/lib/libaudioflinger.so:system/lib/libaudioflinger.so \
    vendor/xolo/era4g/proprietary/lib/libaudiopolicyservice.so:system/lib/libaudiopolicyservice.so \
    vendor/xolo/era4g/proprietary/lib/libaudiopolicy.so:system/lib/libaudiopolicy.so \
    vendor/xolo/era4g/proprietary/lib/libaudio-resampler.so:system/lib/libaudio-resampler.so \
    vendor/xolo/era4g/proprietary/lib/libaudioresampler.so:system/lib/libaudioresampler.so \
    vendor/xolo/era4g/proprietary/lib/libaudioutils.so:system/lib/libaudioutils.so \
    vendor/xolo/era4g/proprietary/lib/libboost.so:system/lib/libboost.so \
    vendor/xolo/era4g/proprietary/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so \
    vendor/xolo/era4g/proprietary/lib/libGLESv1_CM.so:system/lib/libGLESv1_CM.so \
    vendor/xolo/era4g/proprietary/lib/libGLESv2.so:system/lib/libGLESv2.so \
    vendor/xolo/era4g/proprietary/lib/libengbt.so:system/lib/libengbt.so \
    vendor/xolo/era4g/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/xolo/era4g/proprietary/lib/libmemoryheapion.so:system/lib/libmemoryheapion.so \
    vendor/xolo/era4g/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    vendor/xolo/era4g/proprietary/bin/phoneserver:system/bin/phoneserver \
    vendor/xolo/era4g/proprietary/bin/rild_sp:system/bin/rild_sp \
    vendor/xolo/era4g/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/xolo/era4g/proprietary/lib/libril_sp.so:system/lib/libril_sp.so \
    vendor/xolo/era4g/proprietary/lib/libreference-ril_sp.so:system/lib/libreference-ril_sp.so \
    vendor/xolo/era4g/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/xolo/era4g/proprietary/lib/librilutils_sp.so:system/lib/librilutils_sp.so \
    vendor/xolo/era4g/proprietary/lib/libatchannel.so:system/lib/libatchannel.so \
    vendor/xolo/era4g/proprietary/bin/modemd:system/bin/modemd \
    vendor/xolo/era4g/proprietary/bin/modem_control:system/bin/modem_control \
    vendor/xolo/era4g/proprietary/bin/modemDriver_vpad_main:system/bin/modemDriver_vpad_main \
    vendor/xolo/era4g/proprietary/bin/refnotify:system/bin/refnotify \
    vendor/xolo/era4g/proprietary/lib/hw/camera.sc8830.so:system/lib/hw/camera.sc8830.so \
    vendor/xolo/era4g/proprietary/lib/hw/power.sc8830.so:system/lib/hw/power.sc8830.so \
    vendor/xolo/era4g/proprietary/lib/hw/sensors.sc8830.so:system/lib/hw/sensors.sc8830.so \
    vendor/xolo/era4g/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/xolo/era4g/proprietary/lib/hw/gralloc.sc8830.so:system/lib/hw/gralloc.sc8830.so \
    vendor/xolo/era4g/proprietary/lib/hw/hwcomposer.sc8830.so:system/lib/hw/hwcomposer.sc8830.so \
    vendor/xolo/era4g/proprietary/lib/hw/sprd_gsp.sc8830.so:system/lib/hw/sprd_gsp.sc8830.so \
    vendor/xolo/era4g/proprietary/lib/hw/lights.sc8830.so:system/lib/hw/lights.sc8830.so \
    vendor/xolo/era4g/proprietary/lib/hw/audio.primary.sc8830.so:system/lib/hw/audio.primary.sc8830.so \
    vendor/xolo/era4g/proprietary/lib/hw/audio_policy.sc8830.so:system/lib/hw/audio_policy.sc8830.so \
    vendor/xolo/era4g/proprietary/lib/libomx_avcdec_hw_sprd.so:system/lib/libomx_avcdec_hw_sprd.so \
    vendor/xolo/era4g/proprietary/lib/libomx_avcdec_sw_sprd.so:system/lib/libomx_avcdec_sw_sprd.so \
    vendor/xolo/era4g/proprietary/lib/libomx_avcenc_hw_sprd.so:system/lib/libomx_avcenc_hw_sprd.so \
    vendor/xolo/era4g/proprietary/lib/libomx_m4vh263dec_hw_sprd.so:system/lib/libomx_m4vh263dec_hw_sprd.so \
    vendor/xolo/era4g/proprietary/lib/libomx_m4vh263dec_sw_sprd.so:system/lib/libomx_m4vh263dec_sw_sprd.so \
    vendor/xolo/era4g/proprietary/lib/libomx_m4vh263enc_hw_sprd.so:system/lib/libomx_m4vh263enc_hw_sprd.so \
    vendor/xolo/era4g/proprietary/lib/libomx_mp3dec_sprd.so:system/lib/libomx_mp3dec_sprd.so \
    vendor/xolo/era4g/proprietary/lib/libomx_vpxdec_hw_sprd.so:system/lib/libomx_vpxdec_hw_sprd.so \
    vendor/xolo/era4g/proprietary/lib/libomxvpu.so:system/lib/libomxvpu.so \
    vendor/xolo/era4g/proprietary/lib/libstagefrighthw_cm.so:system/lib/libstagefrighthw_cm.so \
    vendor/xolo/era4g/proprietary/lib/libaf.so:system/lib/libaf.so \
    vendor/xolo/era4g/proprietary/lib/libae.so:system/lib/libae.so \
    vendor/xolo/era4g/proprietary/lib/libawb.so:system/lib/libawb.so \
    vendor/xolo/era4g/proprietary/lib/libstagefright_sprd_h264dec.so:system/lib/libstagefright_sprd_h264dec.so \
    vendor/xolo/era4g/proprietary/lib/libstagefright_sprd_h264enc.so:system/lib/libstagefright_sprd_h264enc.so \
    vendor/xolo/era4g/proprietary/lib/libstagefright_sprd_mp3dec.so:system/lib/libstagefright_sprd_mp3dec.so \
    vendor/xolo/era4g/proprietary/lib/libstagefright_sprd_mpeg4dec.so:system/lib/libstagefright_sprd_mpeg4dec.so \
    vendor/xolo/era4g/proprietary/lib/libstagefright_sprd_mpeg4enc.so:system/lib/libstagefright_sprd_mpeg4enc.so \
    vendor/xolo/era4g/proprietary/lib/libstagefright_sprd_soft_h264dec.so:system/lib/libstagefright_sprd_soft_h264dec.so \
    vendor/xolo/era4g/proprietary/lib/libstagefright_sprd_soft_mpeg4dec.so:system/lib/libstagefright_sprd_soft_mpeg4dec.so \
    vendor/xolo/era4g/proprietary/lib/libstagefright_sprd_vpxdec.so:system/lib/libstagefright_sprd_vpxdec.so \
    vendor/xolo/era4g/proprietary/lib/libeng-audio.so:system/lib/libeng-audio.so \
    vendor/xolo/era4g/proprietary/lib/libdumpdata.so:system/lib/libdumpdata.so \
    vendor/xolo/era4g/proprietary/lib/libnvexchange.so:system/lib/libnvexchange.so \
    vendor/xolo/era4g/proprietary/lib/liblsc.so:system/lib/liblsc.so \
    vendor/xolo/era4g/proprietary/lib/libhwui.so:system/lib/libhwui.so \
    vendor/xolo/era4g/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/xolo/era4g/proprietary/lib/drm/libdrmomaplugin.so:system/lib/drm/libdrmomaplugin.so \
    vendor/xolo/era4g/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/xolo/era4g/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/xolo/era4g/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/xolo/era4g/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/xolo/era4g/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/xolo/era4g/proprietary/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
    vendor/xolo/era4g/proprietary/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd
